In [1]:
import numpy as np

The Basics

In [12]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


Get Dimension

In [6]:
b.ndim

2

Get Shape

In [7]:
b.shape

(2, 3)

Type

In [8]:
b.dtype

dtype('int64')

Byte and Size

In [9]:
a.itemsize

8

In [10]:
a.nbytes

24

Accessing /changing specific element

In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
a[1,5]

np.int64(13)

In [16]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
a[:,2]

array([ 3, 10])

In [18]:
a[1,5]=23

In [21]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 23, 14]])

Initializing different types of arrays

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [26]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [28]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
np.random.rand(4,2)

array([[0.35970739, 0.75539995],
       [0.30589368, 0.60786513],
       [0.54785713, 0.76680192],
       [0.45524626, 0.15634086]])

In [35]:
np.random.randint(-20,7,size=(3,3))

array([[-11,  -5, -18],
       [-19,   4, -13],
       [ -7, -11, -19]])

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
print(z)

z[1][1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics

In [49]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [51]:
a+=2
print(a)

[5 6 7 8]


In [54]:
a*=2
print(a)

[10 12 14 16]


In [55]:
a**2


array([100, 144, 196, 256])

In [56]:
np.sin(a)

array([-0.54402111, -0.53657292,  0.99060736, -0.28790332])

Linear Algebra

In [58]:
a=np.full((2,3),1)
print(a)

b=np.full((3,2),2)
print(b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [59]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [60]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

Statistics

In [62]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.min(stats)

np.int64(1)

In [64]:
np.max(stats)

np.int64(6)

In [66]:
np.sum(stats,axis=0)

array([5, 7, 9])